version: "3.9"

services:
  pulsar_test:
    image: apachepulsar/pulsar:2.7.0
    command: bin/pulsar standalone
    ports:
      - 6650:6650
      - 8080:8080
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    networks:
      - pulsar_network

  consumer:
    build:
      context: consumer/
      dockerfile: Dockerfile
    networks:
      - pulsar_network
    depends_on:
      - pulsar_test

networks:
  - pulsar_network

volumes:
  pulsardata:
  pulsarconf: