version: "3.9"

services:
  pulsar_test:
    image: apachepulsar/pulsar:2.7.0
    command: bin/pulsar standalone
    ports:
      - 6650:6650
      - 8080:8080
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    networks:
      - pulsar_network

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


networks:
  - pulsar_network

volumes:
  pulsardata:
  pulsarconf: