---

- hosts: all
  become: true

  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        state: latest
        update_cache: true

    - name: Install dependencies
      pip:
        name:
          - requests
          - pulsar-client
          - pymongo

  tasks:
    - name: Copy Python script
      copy:
        src: /home/ubuntu/Github-analytic-system-using-pulsar/consumers/{{consumer_file}}
        dest: /home/ubuntu/
    - name: Copy shared_data.json
      copy:
        src: /home/ubuntu/Github-analytic-system-using-pulsar/shared_data.json
        dest: /home/ubuntu/
    - name: Copy helpers.py
      copy:
        src: /home/ubuntu/Github-analytic-system-using-pulsar/helpers.py
        dest: /home/ubuntu/
