---

- hosts: all
  become: true

  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        state: latest
        update_cache: true

    - name: Install dependencies
      pip:
        name:
          - requests
          - pulsar-client
          - pymongo

